# This workflow builds the book with documentation and runs book tests
name: Book

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug scylladb" --health-interval 5s --health-retries 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        # We can't use cache here, or mdbook will complain about multiple candidates for dependency.
        cache: false
    # This is a workaround for https://github.com/actions-rust-lang/setup-rust-toolchain/issues/79
    # and https://github.com/rust-lang/mdBook/issues/2501
    # When either mdbook or setup-rust-toolchain fix the issue, we can remove this.
    - name: Set default toolchain globally
      run: rustup default stable
    - name: Install mdbook
      uses: taiki-e/install-action@v2
      with:
        tool: mdbook
    - name: Build the project
      run: cargo build --examples
    - name: Build the book
      run: mdbook build docs
    - name: Run book tests
      run: mdbook test -L target/debug/deps docs
