# This workflow runs all tests on cassandra to ensure full compatibility
name: Cassandra tests

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: Setup 3-node Cassandra cluster
      run: |
        docker compose -f test/cluster/cassandra/docker-compose.yml up -d --wait
      # A separate step for building to separate measuring time of compilation and testing
    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run tests on cassandra
      run: |
        RUSTFLAGS="--cfg cassandra_tests" RUST_LOG=trace SCYLLA_URI=172.42.0.2:9042 SCYLLA_URI2=172.42.0.3:9042 SCYLLA_URI3=172.42.0.4:9042 cargo test --features "full-serialization" -- --skip test_views_in_schema_info --skip test_large_batch_statements
    - name: Check for stale test keyspaces
      run: SCYLLA_URI=172.42.0.2:9042 cargo run --bin find_stale_test_keyspaces
    - name: Stop the cluster
      if: ${{ always() }}
      run: docker compose -f test/cluster/cassandra/docker-compose.yml stop
    - name: Print the cluster logs
      if: ${{ always() }}
      run: docker compose -f test/cluster/cassandra/docker-compose.yml logs
    - name: Remove cluster
      run: docker compose -f test/cluster/cassandra/docker-compose.yml down
